// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYjS9YibYXAAF_phG8WEEuXz4Q1cDXHg0',
    appId: '1:224098541373:web:18fdfad5154f76f52a2f54',
    messagingSenderId: '224098541373',
    projectId: 'flutterauthen-a7ef2',
    authDomain: 'flutterauthen-a7ef2.firebaseapp.com',
    storageBucket: 'flutterauthen-a7ef2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApb6DM24l1fExPoz_IYNymRrT7upZQbX4',
    appId: '1:224098541373:android:cf9b60cb670822062a2f54',
    messagingSenderId: '224098541373',
    projectId: 'flutterauthen-a7ef2',
    storageBucket: 'flutterauthen-a7ef2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC9dWtBvD_dT9wAfzIXAZiIZTGJ3ZwyeE',
    appId: '1:224098541373:ios:b93c0c3c0b5af2fb2a2f54',
    messagingSenderId: '224098541373',
    projectId: 'flutterauthen-a7ef2',
    storageBucket: 'flutterauthen-a7ef2.appspot.com',
    iosBundleId: 'com.example.onboardingScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC9dWtBvD_dT9wAfzIXAZiIZTGJ3ZwyeE',
    appId: '1:224098541373:ios:0ba2a61f668617262a2f54',
    messagingSenderId: '224098541373',
    projectId: 'flutterauthen-a7ef2',
    storageBucket: 'flutterauthen-a7ef2.appspot.com',
    iosBundleId: 'com.example.onboardingScreen.RunnerTests',
  );
}
